-- Borrado de tablas si existen
IF OBJECT_ID('GRANIZADO.DETALLE_FACTURA','U') IS NOT NULL DROP TABLE GRANIZADO.DETALLE_FACTURA;
IF OBJECT_ID('GRANIZADO.FACTURA','U') IS NOT NULL DROP TABLE GRANIZADO.FACTURA;
IF OBJECT_ID('GRANIZADO.ENVIO','U') IS NOT NULL DROP TABLE GRANIZADO.ENVIO;
IF OBJECT_ID('GRANIZADO.DETALLE_PEDIDO','U') IS NOT NULL DROP TABLE GRANIZADO.DETALLE_PEDIDO;
IF OBJECT_ID('GRANIZADO.PEDIDO_CANCELADO','U') IS NOT NULL DROP TABLE GRANIZADO.PEDIDO_CANCELADO;
IF OBJECT_ID('GRANIZADO.PEDIDO','U') IS NOT NULL DROP TABLE GRANIZADO.PEDIDO;
IF OBJECT_ID('GRANIZADO.CLIENTE','U') IS NOT NULL DROP TABLE GRANIZADO.CLIENTE;
IF OBJECT_ID('GRANIZADO.SILLON','U') IS NOT NULL DROP TABLE GRANIZADO.SILLON;
IF OBJECT_ID('GRANIZADO.MODELO','U') IS NOT NULL DROP TABLE GRANIZADO.MODELO;
IF OBJECT_ID('GRANIZADO.MEDIDA','U') IS NOT NULL DROP TABLE GRANIZADO.MEDIDA;
IF OBJECT_ID('GRANIZADO.MATERIAL','U') IS NOT NULL DROP TABLE GRANIZADO.MATERIAL;
IF OBJECT_ID('GRANIZADO.MADERA','U') IS NOT NULL DROP TABLE GRANIZADO.MADERA;
IF OBJECT_ID('GRANIZADO.RELLENO','U') IS NOT NULL DROP TABLE GRANIZADO.RELLENO;
IF OBJECT_ID('GRANIZADO.TELA','U') IS NOT NULL DROP TABLE GRANIZADO.TELA;
IF OBJECT_ID('GRANIZADO.DETALLE_COMPRA','U') IS NOT NULL DROP TABLE GRANIZADO.DETALLE_COMPRA;
IF OBJECT_ID('GRANIZADO.COMPRA','U') IS NOT NULL DROP TABLE GRANIZADO.COMPRA;
IF OBJECT_ID('GRANIZADO.PROVEEDOR','U') IS NOT NULL DROP TABLE GRANIZADO.PROVEEDOR;
IF OBJECT_ID('GRANIZADO.SUCURSAL','U') IS NOT NULL DROP TABLE GRANIZADO.SUCURSAL;
IF OBJECT_ID('GRANIZADO.DIRECCION','U') IS NOT NULL DROP TABLE GRANIZADO.DIRECCION;
IF OBJECT_ID('GRANIZADO.LOCALIDAD','U') IS NOT NULL DROP TABLE GRANIZADO.LOCALIDAD;
IF OBJECT_ID('GRANIZADO.PROVINCIA','U') IS NOT NULL DROP TABLE GRANIZADO.PROVINCIA;

-- Borrado de Stored Procedures (se agregará en Sección 4)
IF OBJECT_ID('GRANIZADO.MIGRAR_PROVINCIA') IS NOT NULL DROP PROCEDURE GRANIZADO.MIGRAR_PROVINCIA;
-- (...se listarán todas después...)

-- Borrado del esquema si existe
IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'GRANIZADO')
  DROP SCHEMA GRANIZADO;
GO


-- Crear esquema
CREATE SCHEMA GRANIZADO;
GO

-- Tabla PROVINCIA
CREATE TABLE GRANIZADO.PROVINCIA (
  provincia_id INT IDENTITY(1,1) NOT NULL,
  prov_nombre NVARCHAR(255) NOT NULL
);

-- Tabla LOCALIDAD
CREATE TABLE GRANIZADO.LOCALIDAD (
  localidad_id INT IDENTITY(1,1) NOT NULL,
  provincia_id INT NOT NULL,
  localidad_nombre NVARCHAR(255) NOT NULL
);

-- Tabla DIRECCION
CREATE TABLE GRANIZADO.DIRECCION (
  direccion_id INT IDENTITY(1,1) NOT NULL,
  localidad_id INT NOT NULL,
  direccion_calle NVARCHAR(255) NOT NULL,
  dir_num_calle NVARCHAR(255) NOT NULL
);

-- Tabla SUCURSAL
CREATE TABLE GRANIZADO.SUCURSAL (
  suc_id INT IDENTITY(1,1) NOT NULL,
  direccion_id INT NOT NULL,
  Sucursal_NroSucursal INT NOT NULL,
  Sucursal_telefono NVARCHAR(255),
  Sucursal_mail NVARCHAR(255)
);



-- Tabla PROVEEDOR
CREATE TABLE GRANIZADO.PROVEEDOR (
  prov_id INT IDENTITY(1,1) NOT NULL,
  direccion_id INT NOT NULL,
  Proveedor_RazonSocial NVARCHAR(255) NOT NULL,
  Proveedor_Telefono NVARCHAR(255),
  Proveedor_Mail NVARCHAR(255)
);

-- Tabla COMPRA
CREATE TABLE GRANIZADO.COMPRA (
  compra_id DECIMAL(18,0) NOT NULL,
  suc_id INT NOT NULL,
  prov_id INT NOT NULL,
  Compra_Fecha DATETIME2(6),
  Compra_Total DECIMAL(18,2)
);


-- Tabla DETALLE_COMPRA
CREATE TABLE GRANIZADO.DETALLE_COMPRA (
  id_det_compra INT IDENTITY(1,1) NOT NULL,
  compra_id DECIMAL(18,0) NOT NULL,
  mat_id INT NOT NULL,
  Detalle_Compra_Precio DECIMAL(18,2),
  Detalle_Compra_Cantidad DECIMAL(18,0),
  Detalle_Compra_SubTotal DECIMAL(18,2)
);

-- Tabla MATERIAL
CREATE TABLE GRANIZADO.MATERIAL (
  mat_id INT IDENTITY(1,1) NOT NULL,
  Material_Tipo NVARCHAR(255),
  Material_Nombre NVARCHAR(255),
  Material_Descripcion NVARCHAR(255),
  Material_Precio DECIMAL(38,2)
);

-- Tabla MADERA
CREATE TABLE GRANIZADO.MADERA (
  madera_id INT IDENTITY(1,1) NOT NULL,
  Madera_Color NVARCHAR(255),
  Madera_Dureza NVARCHAR(255)
);

-- Tabla TELA
CREATE TABLE GRANIZADO.TELA (
  tela_id INT IDENTITY(1,1) NOT NULL,
  Tela_Color NVARCHAR(255),
  Tela_Textura NVARCHAR(255)
);

-- Tabla RELLENO
CREATE TABLE GRANIZADO.RELLENO (
  relleno_id INT IDENTITY(1,1) NOT NULL,
  Relleno_Densidad DECIMAL(38,2)
);

-- Tabla MEDIDA
CREATE TABLE GRANIZADO.MEDIDA (
  med_id INT IDENTITY(1,1) NOT NULL,
  precio DECIMAL(18,2),
  Sillon_Medida_Alto DECIMAL(18,2),
  Sillon_Medida_Ancho DECIMAL(18,2),
  Sillon_Medida_Profundidad DECIMAL(18,2)
);

-- Tabla MODELO
CREATE TABLE GRANIZADO.MODELO (
  mod_id INT IDENTITY(1,1) NOT NULL,
  nombre_modelo NVARCHAR(255),
  precio_modelo DECIMAL(18,2)
);

-- Tabla SILLON
CREATE TABLE GRANIZADO.SILLON (
  Sillon_Codigo BIGINT NOT NULL,
  Sillon_Modelo_Codigo INT,
  med_id INT,
  mat_id INT,
  Sillon_Modelo_Descripcion NVARCHAR(255)
);

-- Tabla CLIENTE
CREATE TABLE GRANIZADO.CLIENTE (
  cli_id INT IDENTITY(1,1) NOT NULL,
  Cliente_nombre NVARCHAR(255),
  Cliente_Apellido NVARCHAR(255),
  Cliente_FechaNacimiento DATETIME2(6),
  direccion_id INT NOT NULL,
  Cliente_Telefono NVARCHAR(255),
  Cliente_Mail NVARCHAR(255)
);

-- Tabla PEDIDO
CREATE TABLE GRANIZADO.PEDIDO (
  Pedido_Numero DECIMAL(18,0) NOT NULL,
  Pedido_Fecha DATETIME2(6),
  suc_id INT,
  cli_id INT,
  Pedido_Total DECIMAL(18,2),
  Pedido_Estado NVARCHAR(255),
  Pedido_Cancelacion_Fecha DATETIME2(6),
  Pedido_Cancelacion_Motivo VARCHAR(255)
);

-- Tabla PEDIDO_CANCELADO
CREATE TABLE GRANIZADO.PEDIDO_CANCELADO (
  Pedido_Numero DECIMAL(18,0) NOT NULL,
  Pedido_Cancelacion_Fecha DATETIME2(6),
  Pedido_Cancelacion_Motivo VARCHAR(255)
);

-- Tabla DETALLE_PEDIDO
CREATE TABLE GRANIZADO.DETALLE_PEDIDO (
  det_pedido_id INT IDENTITY(1,1) NOT NULL,
  Pedido_Numero DECIMAL(18,0) NOT NULL,
  Sillon_Codigo BIGINT,
  Detalle_Pedido_Cantidad BIGINT,
  Detalle_Pedido_Precio DECIMAL(18,2),
  Detalle_Pedido_SubTotal DECIMAL(18,2)
);

-- Tabla FACTURA
CREATE TABLE GRANIZADO.FACTURA (
  fact_id INT IDENTITY(1,1) NOT NULL,
  cli_id INT,
  suc_id INT,
  Factura_Numero BIGINT,
  Factura_Fecha DATETIME2(6),
  Factura_Total DECIMAL(38,2)
);

-- Tabla DETALLE_FACTURA
CREATE TABLE GRANIZADO.DETALLE_FACTURA (
  det_fact_id INT IDENTITY(1,1) NOT NULL,
  det_pedido_id INT,
  fact_id INT,
  Detalle_Factura_Precio DECIMAL(18,2),
  Detalle_Factura_Cantidad DECIMAL(18,0),
  Detalle_Factura_SubTotal DECIMAL(18,2)
);

-- Tabla ENVIO
CREATE TABLE GRANIZADO.ENVIO (
  Envio_Numero DECIMAL(18,0) NOT NULL,
  fact_id INT,
  Envio_Fecha_Programada DATETIME2(6),
  Envio_Fecha DATETIME2(6),
  Envio_ImporteTraslado DECIMAL(18,2),
  Envio_ImporteSubida DECIMAL(18,2),
  Envio_Total DECIMAL(18,2)
);
GO


-- PRIMARY KEYS
ALTER TABLE GRANIZADO.PROVINCIA
  ADD CONSTRAINT PK_PROVINCIA PRIMARY KEY (provincia_id);

ALTER TABLE GRANIZADO.LOCALIDAD
  ADD CONSTRAINT PK_LOCALIDAD PRIMARY KEY (localidad_id);

ALTER TABLE GRANIZADO.DIRECCION
  ADD CONSTRAINT PK_DIRECCION PRIMARY KEY (direccion_id);

ALTER TABLE GRANIZADO.SUCURSAL
  ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY (suc_id);

ALTER TABLE GRANIZADO.PROVEEDOR
  ADD CONSTRAINT PK_PROVEEDOR PRIMARY KEY (prov_id);

ALTER TABLE GRANIZADO.COMPRA
  ADD CONSTRAINT PK_COMPRA PRIMARY KEY (compra_id);

ALTER TABLE GRANIZADO.DETALLE_COMPRA
  ADD CONSTRAINT PK_DETALLE_COMPRA PRIMARY KEY (id_det_compra);

ALTER TABLE GRANIZADO.MATERIAL
  ADD CONSTRAINT PK_MATERIAL PRIMARY KEY (mat_id);

ALTER TABLE GRANIZADO.MADERA
  ADD CONSTRAINT PK_MADERA PRIMARY KEY (madera_id);

ALTER TABLE GRANIZADO.TELA
  ADD CONSTRAINT PK_TELA PRIMARY KEY (tela_id);

ALTER TABLE GRANIZADO.RELLENO
  ADD CONSTRAINT PK_RELLENO PRIMARY KEY (relleno_id);

ALTER TABLE GRANIZADO.MEDIDA
  ADD CONSTRAINT PK_MEDIDA PRIMARY KEY (med_id);

ALTER TABLE GRANIZADO.MODELO
  ADD CONSTRAINT PK_MODELO PRIMARY KEY (mod_id);

ALTER TABLE GRANIZADO.SILLON
  ADD CONSTRAINT PK_SILLON PRIMARY KEY (Sillon_Codigo);

ALTER TABLE GRANIZADO.CLIENTE
  ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (cli_id);

ALTER TABLE GRANIZADO.PEDIDO
  ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (Pedido_Numero);

ALTER TABLE GRANIZADO.PEDIDO_CANCELADO
  ADD CONSTRAINT PK_PEDIDO_CANCELADO PRIMARY KEY (Pedido_Numero);

ALTER TABLE GRANIZADO.DETALLE_PEDIDO
  ADD CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (det_pedido_id);

ALTER TABLE GRANIZADO.FACTURA
  ADD CONSTRAINT PK_FACTURA PRIMARY KEY (fact_id);

ALTER TABLE GRANIZADO.DETALLE_FACTURA
  ADD CONSTRAINT PK_DETALLE_FACTURA PRIMARY KEY (det_fact_id);

ALTER TABLE GRANIZADO.ENVIO
  ADD CONSTRAINT PK_ENVIO PRIMARY KEY (Envio_Numero);


-- LOCALIDAD → PROVINCIA
ALTER TABLE GRANIZADO.LOCALIDAD
  ADD CONSTRAINT FK_LOCALIDAD_PROVINCIA FOREIGN KEY (provincia_id)
  REFERENCES GRANIZADO.PROVINCIA(provincia_id);

-- DIRECCION → LOCALIDAD
ALTER TABLE GRANIZADO.DIRECCION
  ADD CONSTRAINT FK_DIRECCION_LOCALIDAD FOREIGN KEY (localidad_id)
  REFERENCES GRANIZADO.LOCALIDAD(localidad_id);

-- SUCURSAL → DIRECCION
ALTER TABLE GRANIZADO.SUCURSAL
  ADD CONSTRAINT FK_SUCURSAL_DIRECCION FOREIGN KEY (direccion_id)
  REFERENCES GRANIZADO.DIRECCION(direccion_id);

-- PROVEEDOR → DIRECCION
ALTER TABLE GRANIZADO.PROVEEDOR
  ADD CONSTRAINT FK_PROVEEDOR_DIRECCION FOREIGN KEY (direccion_id)
  REFERENCES GRANIZADO.DIRECCION(direccion_id);

-- COMPRA → SUCURSAL, PROVEEDOR
ALTER TABLE GRANIZADO.COMPRA
  ADD CONSTRAINT FK_COMPRA_SUC FOREIGN KEY (suc_id) REFERENCES GRANIZADO.SUCURSAL(suc_id),
      CONSTRAINT FK_COMPRA_PROV FOREIGN KEY (prov_id) REFERENCES GRANIZADO.PROVEEDOR(prov_id);

-- DETALLE_COMPRA → COMPRA, MATERIAL
ALTER TABLE GRANIZADO.DETALLE_COMPRA
  ADD CONSTRAINT FK_DETCOMPRA_COMPRA FOREIGN KEY (compra_id) REFERENCES GRANIZADO.COMPRA(compra_id),
      CONSTRAINT FK_DETCOMPRA_MAT FOREIGN KEY (mat_id) REFERENCES GRANIZADO.MATERIAL(mat_id);

-- SILLON → MODELO, MEDIDA, MATERIAL
ALTER TABLE GRANIZADO.SILLON
  ADD CONSTRAINT FK_SILLON_MODELO FOREIGN KEY (Sillon_Modelo_Codigo) REFERENCES GRANIZADO.MODELO(mod_id),
      CONSTRAINT FK_SILLON_MEDIDA FOREIGN KEY (med_id) REFERENCES GRANIZADO.MEDIDA(med_id),
      CONSTRAINT FK_SILLON_MATERIAL FOREIGN KEY (mat_id) REFERENCES GRANIZADO.MATERIAL(mat_id);

-- CLIENTE → DIRECCION
ALTER TABLE GRANIZADO.CLIENTE
  ADD CONSTRAINT FK_CLIENTE_DIRECCION FOREIGN KEY (direccion_id)
  REFERENCES GRANIZADO.DIRECCION(direccion_id);

-- PEDIDO → CLIENTE, SUCURSAL
ALTER TABLE GRANIZADO.PEDIDO
  ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (cli_id) REFERENCES GRANIZADO.CLIENTE(cli_id),
      CONSTRAINT FK_PEDIDO_SUC FOREIGN KEY (suc_id) REFERENCES GRANIZADO.SUCURSAL(suc_id);

-- PEDIDO_CANCELADO → PEDIDO
ALTER TABLE GRANIZADO.PEDIDO_CANCELADO
  ADD CONSTRAINT FK_PEDCAN_PED FOREIGN KEY (Pedido_Numero)
  REFERENCES GRANIZADO.PEDIDO(Pedido_Numero);

-- DETALLE_PEDIDO → PEDIDO, SILLON
ALTER TABLE GRANIZADO.DETALLE_PEDIDO
  ADD CONSTRAINT FK_DETPEDIDO_PED FOREIGN KEY (Pedido_Numero) REFERENCES GRANIZADO.PEDIDO(Pedido_Numero),
      CONSTRAINT FK_DETPEDIDO_SILLON FOREIGN KEY (Sillon_Codigo) REFERENCES GRANIZADO.SILLON(Sillon_Codigo);

-- FACTURA → CLIENTE, SUCURSAL
ALTER TABLE GRANIZADO.FACTURA
  ADD CONSTRAINT FK_FACTURA_CLI FOREIGN KEY (cli_id) REFERENCES GRANIZADO.CLIENTE(cli_id),
      CONSTRAINT FK_FACTURA_SUC FOREIGN KEY (suc_id) REFERENCES GRANIZADO.SUCURSAL(suc_id);

-- DETALLE_FACTURA → FACTURA, DETALLE_PEDIDO
ALTER TABLE GRANIZADO.DETALLE_FACTURA
  ADD CONSTRAINT FK_DETFACT_FACT FOREIGN KEY (fact_id) REFERENCES GRANIZADO.FACTURA(fact_id),
      CONSTRAINT FK_DETFACT_PEDIDO FOREIGN KEY (det_pedido_id) REFERENCES GRANIZADO.DETALLE_PEDIDO(det_pedido_id);

-- ENVIO → FACTURA
ALTER TABLE GRANIZADO.ENVIO
  ADD CONSTRAINT FK_ENVIO_FACT FOREIGN KEY (fact_id)
  REFERENCES GRANIZADO.FACTURA(fact_id);
GO
